### ISSUE TITLE
conversion from counts to uT

### ISSUE THREAD

**Issue by anielsen001** [furbrain/CircuitPython_RM3100#1]
I'm curious about the code's calculation of gain to convert from counts to microTesla, found [here](https://github.com/furbrain/CircuitPython_RM3100/blob/dab548109b2b120c00f9a4ce152b9be1f393d7cc/rm3100.py#L169)

The value I get when running this code for 200 cycles is:
`_UT_PER_CYCLE / self.cycle_count = 2.5000/ 200 = 1/80` or 80 LSB/uT

In the the [RM3100 documentation, Table 3.1](https://www.pnicorp.com/download/rm3100-testing-boards-manual/), the value for 200 counts is listed as 75 LSB/uT (with some language about being subject to change).

Any idea which is correct? or maybe it depends upon specific board design? I'm using the PNI RM3100 testing board.

**Comment by furbrain** [comment]
I think I used the numbers from the 50 count cycle details to calculate this. I note that the measured inductance for the coils states 500-600 uH, so I think relying on the measurements for precise magnetic field strengths is not going to be practicable. It will give you field strength to within 5-10% perhaps, but will need proper calibration for more accuracy. I don't have access to a properly controlled magnetic field so can't really comment any further. I don't have a strong feeling between a factor of 2.667 (which gives 75LSB/uT, but only 18.7 LSB/uT at 50 count cycle).

Ultimately I think it will need proper calibration to get accurate field strength numbers.
